# Generated by Django 6.0.3 on 2026-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('user_registered', 'Регистрация пользователя'), ('user_logged_in', 'Вход в систему'), ('user_logged_out', 'Выход из системы'), ('password_changed', 'Изменение пароля'), ('password_recovered', 'Восстановление пароля'), ('image_uploaded', 'Загрузка изображения'), ('image_seeded', 'Автозагрузка изображения (система)'), ('metadata_updated', 'Обновление метаданных'), ('image_deleted', 'Удаление изображения'), ('search_executed', 'Выполнение поиска'), ('stats_viewed', 'Просмотр статистики системы'), ('database_exported', 'Экспорт базы данных'), ('database_imported', 'Импорт базы данных'), ('profile_updated', 'Обновление профиля'), ('email_changed', 'Смена email'), ('admin_user_restrictions_updated', 'Изменение ограничений пользователя администратором'), ('image_liked', 'Добавление публикации в избранное'), ('image_unliked', 'Удаление публикации из избранного')], max_length=50),
        ),
    ]
